kibot:
  version: 1

preflight:
  run_erc: false
  run_drc: false
  check_zone_fills: false
  ignore_unconnected: false

outputs:
  - name: 'schematic_pdf'
    comment: 'Exports the schematic to a PDF file'
    type: 'pdf_sch_print'
    dir: 'pdfs'
    options:
      output: '%f-schematic.%x'
